// Production-container UI verification against an isolated synthetic database.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const { chromium } = require('/opt/ms-playwright-go/package');
(async () => {
  const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
  const checks = [], errors = [], cspErrors = [];
  const checked = name => { checks.push(name); console.log('PASS ' + name); };
  const out = '/data/verification'; fs.mkdirSync(out, { recursive: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    page.on('pageerror', error => errors.push(error.message));
    page.on('console', message => { if (/violates.*Content Security Policy/i.test(message.text())) cspErrors.push(message.text()); });
    await page.goto('http://127.0.0.1:8000/app/');
    await page.getByRole('heading', { name: 'Unlock your workspace' }).waitFor();
    await page.getByLabel('API token', { exact: true }).fill('wrong-token');
    await page.getByRole('button', { name: 'Unlock workspace' }).click();
    await page.locator('#auth-error').getByText('A valid API token is required to unlock this workspace.').waitFor();
    await page.getByLabel('API token', { exact: true }).fill(process.env.APP_API_TOKEN);
    await page.getByRole('button', { name: 'Unlock workspace' }).click();
    await page.getByRole('heading', { name: 'Overview', exact: true }).waitFor();
    assert.deepEqual(await page.locator('.stat-value').allTextContents(), ['1', '1', '0', '0']);
    assert(await page.evaluate(() => !localStorage.length && !sessionStorage.length && !document.cookie));
    checked('Production login accepts the configured token, rejects a wrong token, and keeps it out of browser storage');
    const globalSearch=page.getByLabel('Search saved businesses',{exact:true});
    await globalSearch.fill('no matching fictional business');
    await page.locator('#global-search-results').getByText('No saved businesses match this search.',{exact:true}).waitFor();
    await globalSearch.fill('Synthetic deployment');
    await page.locator('#global-search-results .search-result').waitFor();
    await globalSearch.press('ArrowDown');
    assert(await page.locator('#global-search-results .search-result').evaluate(node=>node===document.activeElement));
    await page.keyboard.press('Enter');
    await page.getByRole('heading',{name:'Two-stage review'}).waitFor();
    assert.equal(await globalSearch.inputValue(),'');
    checked('CRM search opens an authenticated saved business by keyboard, handles no matches and clears its query');
    await page.getByRole('heading', { name: 'Two-stage review' }).waitFor();
    await page.locator('#lead-content').getByText('Need unconfirmed', { exact: true }).waitFor();
    assert.equal(await page.getByLabel('Notes', { exact: true }).inputValue(), 'Synthetic restart verification; no business contacted.');
    await page.getByRole('button', { name: 'Generate outreach draft', exact: true }).click();
    await page.getByLabel('Outreach draft', { exact: true }).waitFor();
    assert.match(await page.getByLabel('Outreach draft', { exact: true }).inputValue(), /I'd like to understand/);
    assert(await page.getByRole('button', { name: 'Create workflow draft', exact: true }).isDisabled());
    checked('Persisted fixture evidence and contact notes render; unknown needs do not unlock workflows');
    await page.getByRole('button', { name: 'Close', exact: true }).click();
    await page.getByRole('link',{name:'Leads & research',exact:true}).click();
    await page.getByRole('heading',{name:'Leads & research',exact:true}).waitFor();
    await page.getByRole('button',{name:'Ready for review',exact:true}).click();
    assert.equal(await page.locator('tbody tr').count(),1);
    assert.equal(await page.getByLabel('Filter leads',{exact:true}).inputValue(),'ready');
    await page.getByRole('button',{name:'Confirmed needs',exact:true}).click();
    await page.getByRole('heading',{name:'No leads in this view'}).waitFor();
    assert.equal(await page.getByRole('button',{name:'Confirmed needs',exact:true}).getAttribute('aria-pressed'),'true');
    await page.getByRole('button',{name:'All leads',exact:true}).click();
    assert.equal(await page.locator('tbody tr').count(),1);
    await page.screenshot({path:out+'/leads-desktop.png',fullPage:true});
    checked('CRM saved views and filters remain synchronized and keep public fit separate from confirmed need');
    await page.getByRole('link', { name: 'Connections', exact: true }).click();
    await page.getByText('Prerequisites detected', { exact: true }).waitFor();
    await page.getByText('Sandbox API available', { exact: true }).waitFor();
    await page.getByRole('link', { name: 'Discover & import', exact: true }).click();
    assert(await page.getByRole('button', { name: /^Start live pilot/ }).isEnabled());
    checked('Bundled collector availability reaches the production UI');
    await page.getByRole('link', { name: 'Overview', exact: true }).click();
    await page.getByRole('heading', { name: 'Overview', exact: true }).waitFor();
    await page.screenshot({ path: out + '/desktop.png', fullPage: true });
    await page.setViewportSize({ width: 390, height: 844 });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: out + '/mobile.png', fullPage: true });
    checked('Production assets run under CSP and fit desktop and mobile viewports');
    await page.reload();
    await page.getByRole('heading', { name: 'Unlock your workspace' }).waitFor();
    assert(await page.evaluate(() => !localStorage.length && !sessionStorage.length));
    assert(await globalSearch.isDisabled());
    assert.equal(await page.locator('#global-search-results').textContent(),'');
    checked('Reload clears workspace access');
    assert.deepEqual(errors, []); assert.deepEqual(cspErrors, []);
    fs.writeFileSync(out + '/browser-report.json', JSON.stringify({ checked_at: new Date().toISOString(), checks,
      javascript_errors: errors, csp_errors: cspErrors, synthetic_data: true, businesses_contacted: false }, null, 2));
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
