// Fictional-only browser integration. No calls, email or real-lead modifications.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const { chromium, request: requestAPI } = require('/opt/ms-playwright-go/package');
(async () => {
  const base = process.env.CLIENT_TEST_URL || 'http://127.0.0.1:8001';
  const out = process.env.CLIENT_TEST_OUT || '/out';
  const token = process.env.APP_API_TOKEN || 'synthetic-workspace-fixture-only';
  const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
  const checks = [], errors = [], csp = [];
  const checked = value => { checks.push(value); console.log('PASS '+value); };
  const page = await browser.newPage({ viewport: { width:1440, height:1000 }, acceptDownloads:true });
  const api = await requestAPI.newContext({ baseURL:base, extraHTTPHeaders:{ Authorization:'Bearer '+token } });
  const waitNotice = text => page.locator('#notice').getByText(text,{exact:true}).waitFor();
  const local = value => { const d = new Date(value); return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,19).replace(/:00$/, ''); };
  const waitRun = async (id, expected) => {
    for (let i=0;i<80;i++) {
      const r = await (await api.get('/workflow-runs/'+id)).json();
      if(r.status===expected) return r;
      await new Promise(resolve=>setTimeout(resolve,200));
    }
    throw new Error('Run did not reach '+expected);
  };
  try {
    page.on('pageerror', e=>errors.push(e.message));
    page.on('console', m=>{if(/violates.*Content Security Policy/i.test(m.text()))csp.push(m.text());});
    await page.goto(base+'/app/#clients');
    await page.getByLabel('API token',{exact:true}).fill(token);
    await page.getByRole('button',{name:'Unlock workspace'}).click();
    await page.getByRole('heading', { name: 'Clients', exact: true }).waitFor();
    assert.equal(await page.getByRole('button',{name:/Send email/i}).count(),0);
    checked('Client workspace is authenticated and exposes sandbox setup without a live-send control');
    await page.getByRole('button',{name:'Create fictional client example',exact:true}).click();
    await waitNotice('Fictional lead and reminder workflow are ready. Record demo authorization to onboard it.');
    await page.getByLabel('Client business',{exact:true}).selectOption({label:'Demo Reminder Studio (Mock) · fictional'});
    await page.getByLabel('Client contact name',{exact:true}).fill('Synthetic browser operator');
    await page.getByLabel('Client timezone',{exact:true}).fill('Asia/Karachi');
    await page.getByLabel('Authorization reference',{exact:true}).fill('Fictional approval <img src=x onerror=alert(1)>');
    await page.getByLabel('Business authorization is recorded; fictional authorization is only for demo businesses.',{exact:true}).check();
    const createdPromise=page.waitForResponse(r=>r.url().endsWith('/clients')&&r.request().method()==='POST');
    await page.getByRole('button',{name:'Create client profile',exact:true}).click();
    const created=await createdPromise;assert.equal(created.status(),201);
    const client=await created.json();assert.equal(client.is_demo,true);
    await waitNotice('Client profile saved. Review authorization before activating it.');
    const card=()=>page.locator(`[data-client-id="${client.id}"]`);
    assert.equal(await card().locator('img').count(),0);
    assert(await card().getByRole('button',{name:'Activate client',exact:true}).isDisabled());
    const deploymentPromise=page.waitForResponse(r=>r.url().endsWith('/clients/'+client.id+'/deployments')&&r.request().method()==='POST');
    await card().getByRole('button',{name:'Create sandbox setup',exact:true}).click();
    const deployment=await (await deploymentPromise).json();
    await waitNotice('Sandbox setup saved. Run a sandbox proof, then validate it.');
    const setup=()=>page.locator(`[data-deployment-id="${deployment.id}"]`);
    await setup().getByRole('button',{name:'Validate sandbox setup',exact:true}).click();
    await waitNotice('Validation needs attention. Review the checks and run a successful sandbox proof.');
    assert.match(await setup().textContent(),/Needs attention: Client must be active/);
    assert.equal(await setup().getByRole('button',{name:'Activate sandbox setup',exact:true}).count(),0);
    checked('Fictional onboarding keeps authorization text safe and blocks deployment activation while client authorization review is pending');
    await card().getByLabel('I reviewed this client authorization.',{exact:true}).check();
    await card().getByRole('button',{name:'Activate client',exact:true}).click();
    await waitNotice('Client activated. Validate a workflow before activating its sandbox setup.');
    await setup().getByRole('button',{name:'Open sandbox lab for a proof →',exact:true}).click();
    await page.getByRole('heading', { name: 'Automation lab', exact: true }).waitFor();
    await page.getByLabel('Reminder workflow',{exact:true}).selectOption(deployment.workflow_id);
    await page.getByLabel('Appointment starts',{exact:true}).fill(local(Date.now()+3600000));
    await page.getByLabel('Reminder time',{exact:true}).fill(local(Date.now()+3000));
    await page.getByLabel('Permission recorded for this synthetic contact',{exact:true}).check();
    await page.getByLabel('I understand this creates an unsent sandbox preview',{exact:true}).check();
    let appointmentPromise=page.waitForResponse(r=>r.url().endsWith('/appointments')&&r.request().method()==='POST');
    await page.getByRole('button',{name:'Schedule sandbox reminder',exact:true}).click();
    const proof=await (await appointmentPromise).json();
    await waitRun(proof.run_id,'succeeded');
    await page.getByRole('link',{name:'Clients',exact:true}).click();
    await page.getByRole('heading', { name: 'Clients', exact: true }).waitFor();
    await setup().getByRole('button',{name:'Validate sandbox setup',exact:true}).click();
    await waitNotice('Sandbox setup validated. Review and confirm activation.');
    assert(await setup().getByRole('button',{name:'Activate sandbox setup',exact:true}).isDisabled());
    await setup().getByLabel('I reviewed the checks and approve this sandbox setup.',{exact:true}).check();
    await setup().getByRole('button',{name:'Activate sandbox setup',exact:true}).click();
    await waitNotice('Sandbox setup activated. Client reminders can now use it.');
    checked('A real local sandbox proof unlocks reviewed activation with explicit confirmation');
    await setup().getByRole('button',{name:'Schedule client reminder',exact:true}).click();
    await page.getByLabel('Client deployment (optional)',{exact:true}).waitFor();
    assert.equal(await page.getByLabel('Client deployment (optional)',{exact:true}).inputValue(),deployment.id);
    assert(await page.getByLabel('Reminder workflow',{exact:true}).isDisabled());
    await page.getByLabel('Appointment starts',{exact:true}).fill(local(Date.now()+3600000));
    await page.getByLabel('Reminder time',{exact:true}).fill(local(Date.now()+600000));
    await page.getByLabel('Permission recorded for this synthetic contact',{exact:true}).check();
    await page.getByLabel('I understand this creates an unsent sandbox preview',{exact:true}).check();
    appointmentPromise=page.waitForResponse(r=>r.url().endsWith('/deployments/'+deployment.id+'/appointments')&&r.request().method()==='POST');
    await page.getByRole('button',{name:'Schedule sandbox reminder',exact:true}).click();
    const managedResponse=await appointmentPromise;assert.equal(managedResponse.status(),202);
    const managed=await managedResponse.json();assert.equal(managed.deployment_id,deployment.id);
    await waitRun(managed.run_id,'waiting');
    await page.getByRole('link',{name:'Clients',exact:true}).click();
    await setup().getByRole('button',{name:'Pause setup',exact:true}).click();
    await waitNotice('Setup paused. Pending managed reminders will stop.');
    assert.equal((await waitRun(managed.run_id,'skipped')).stop_reason,'deployment_inactive');
    assert.deepEqual(await (await api.get('/workflow-outbox?run_id='+managed.run_id)).json(),[]);
    const downloadPromise=page.waitForEvent('download');
    await card().getByRole('button',{name:'Download client handoff',exact:true}).click();
    const download=await downloadPromise;
    const handoff=JSON.parse(fs.readFileSync(await download.path(),'utf8'));
    assert.equal(handoff.client.is_demo,true);assert.equal(handoff.credentials_included,false);
    assert.equal(handoff.deployments[0].status,'paused');assert(!JSON.stringify(handoff).includes(token));
    checked('UI routes reminders through the selected deployment; pausing stops pending work and downloads a handoff without credentials');
    await page.getByRole('link',{name:'Follow-up tasks',exact:true}).click();
    await page.getByRole('heading', { name: 'Follow-up tasks', exact: true }).waitFor();
    await page.getByLabel('Task business',{exact:true}).selectOption(client.business_id);
    await page.getByLabel('Task title',{exact:true}).fill('Synthetic overdue task <img src=x onerror=alert(1)>');
    await page.getByLabel('Task notes',{exact:true}).fill('Fictional note only.');
    await page.getByLabel('Task due time',{exact:true}).fill(local(Date.now()-3600000));
    let accepted;
    const taskRoute='**/businesses/'+client.business_id+'/tasks';
    await page.route(taskRoute,async route=>{const response=await route.fetch();accepted=await response.json();await route.abort('failed');});
    await page.getByRole('button',{name:'Save follow-up task',exact:true}).click();
    await page.locator('#notice.error').getByText('The server could not be reached. Check the connection and try again.',{exact:true}).waitFor();
    await page.unroute(taskRoute);
    await page.getByRole('button',{name:'Refresh tasks',exact:true}).click();
    await page.locator(`[data-task-id="${accepted.id}"]`).waitFor();
    assert.equal(await page.getByLabel('Task title',{exact:true}).inputValue(),'Synthetic overdue task <img src=x onerror=alert(1)>');
    const retryPromise=page.waitForResponse(r=>r.url().endsWith('/businesses/'+client.business_id+'/tasks')&&r.request().method()==='POST');
    await page.getByRole('button',{name:'Save follow-up task',exact:true}).click();
    assert.equal((await (await retryPromise).json()).id,accepted.id);
    await waitNotice('Follow-up task saved. No message was sent.');
    const taskCard=()=>page.locator(`[data-task-id="${accepted.id}"]`);
    assert.equal(await taskCard().locator('img').count(),0);
    assert.equal((await (await api.get('/tasks?business_id='+client.business_id)).json()).filter(t=>t.title.includes('Synthetic overdue')).length,1);
    checked('Lost-response task retry reuses its saved key and safely renders operator text without duplicate tasks');
    await page.getByRole('link',{name:'Operations',exact:true}).click();
    await page.locator(`[data-alert-id="${accepted.id}"]`).waitFor();
    await page.getByLabel('Include fictional demo records',{exact:true}).uncheck();
    await page.getByText(/Fictional demo records excluded/).waitFor();
    assert.equal(await page.locator(`[data-alert-id="${accepted.id}"]`).count(),0);
    await page.getByLabel('Include fictional demo records',{exact:true}).check();
    await page.locator(`[data-alert-id="${accepted.id}"]`).waitFor();
    await page.getByRole('link',{name:'Follow-up tasks',exact:true}).click();
    await taskCard().getByRole('button',{name:'Complete task',exact:true}).click();
    await waitNotice('Task completed.');
    await page.getByRole('link',{name:'Operations',exact:true}).click();
    await page.getByRole('button',{name:'Refresh operations',exact:true}).click();
    await page.getByText(/Checked.*Fictional demo records included/).waitFor();
    assert.equal(await page.locator(`[data-alert-id="${accepted.id}"]`).count(),0);
    checked('Operations explicitly filters demo alerts and clears the overdue alert when its task is completed');
    await page.getByRole('link',{name:'Clients',exact:true}).click();
    await setup().getByRole('button',{name:'Validate sandbox setup',exact:true}).click();
    await waitNotice('Sandbox setup validated. Review and confirm activation.');
    await setup().getByLabel('I reviewed the checks and approve this sandbox setup.',{exact:true}).check();
    await setup().getByRole('button',{name:'Activate sandbox setup',exact:true}).click();
    await waitNotice('Sandbox setup activated. Client reminders can now use it.');
    await card().getByRole('button',{name:'Pause client',exact:true}).click();
    await waitNotice('Client paused. Pending managed work will stop; submitted messages cannot be recalled.');
    await page.getByRole('link',{name:'Operations',exact:true}).click();
    const blockedSetup=page.locator(`[data-alert-id="${deployment.id}"]`);
    await blockedSetup.getByText('Deployment validation stale',{exact:true}).waitFor();
    await blockedSetup.getByRole('link',{name:'Review client setup →',exact:true}).click();
    await page.getByRole('heading',{name:'Clients',exact:true}).waitFor();
    await setup().getByRole('button',{name:'Pause setup',exact:true}).click();
    await waitNotice('Setup paused. Pending managed reminders will stop.');
    checked('Operations flags a blocked active setup and links to client review without silently reactivating it');
    fs.mkdirSync(out,{recursive:true});
    await page.getByRole('link',{name:'Clients',exact:true}).click();
    await page.getByRole('heading',{name:'Clients',exact:true}).waitFor();
    await page.screenshot({path:out+'/clients-desktop.png',fullPage:true});
    await page.setViewportSize({width:390,height:844});
    for(const label of ['Clients','Follow-up tasks','Operations']) {
      await page.getByRole('link',{name:label,exact:true}).click();
      const titles={'Clients':'Clients','Follow-up tasks':'Follow-up tasks','Operations':'Operations'};
      await page.getByRole('heading',{name:titles[label],exact:true}).waitFor();
      assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),label);
    }
    await page.screenshot({path:out+'/operations-mobile.png',fullPage:true});
    assert.deepEqual(errors,[]);assert.deepEqual(csp,[]);
    checked('Client, task and operations views fit mobile/desktop with no JavaScript or CSP errors');
    await page.getByRole('link',{name:'Clients',exact:true}).click();
    let release;const gate=new Promise(resolve=>release=resolve);
    await page.route('**/clients/'+client.id+'/history?limit=100',async route=>{await gate;await route.continue();});
    const delayedResponse=page.waitForResponse(r=>r.url().endsWith('/clients/'+client.id+'/history?limit=100'));
    await card().getByRole('button',{name:'View client history',exact:true}).click();
    await page.getByRole('button',{name:'Lock',exact:true}).click();
    release();await delayedResponse;await page.getByLabel('API token',{exact:true}).waitFor();
    assert.doesNotMatch(await page.locator('#content').textContent(),/Synthetic browser operator|Fictional approval/);
    await page.reload();await page.getByLabel('API token',{exact:true}).waitFor();
    assert.equal(await page.evaluate(()=>localStorage.length+sessionStorage.length),0);
    checked('Lock and reload clear client/task access; an in-flight history response cannot restore private workspace data');
    fs.writeFileSync(out+'/client-browser-report.json',JSON.stringify({checked_at:new Date().toISOString(),checks,javascript_errors:errors,csp_errors:csp,synthetic_data:true,businesses_contacted:false,email_sent:false,client_id:client.id,deployment_id:deployment.id},null,2));
  } finally {await api.dispose();await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
