// Read-only verification of the previously collected five-business live cohort.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const { chromium } = require('/opt/ms-playwright-go/package');
(async () => {
  const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
  const checks = [], errors = [];
  const checked = name => { checks.push(name); console.log('PASS ' + name); };
  try {
    const page = await browser.newPage({ viewport: { width: 1600, height: 1000 } });
    page.on('pageerror', error => errors.push(error.message));
    await page.goto('http://127.0.0.1:8000/app/');
    await page.getByRole('heading', { name: 'Overview', exact: true }).waitFor();
    const values = await page.locator('.stat-value').allTextContents();
    assert.deepEqual(values, ['5', '5', '0', '0']);
    checked('Five existing real leads are prospect-review ready; zero business-confirmed gaps');
    const search=page.getByLabel('Search saved businesses',{exact:true});
    await search.fill('Med');
    const matches=page.locator('#global-search-results .search-result');
    assert.equal(await matches.count(),5);
    await search.press('ArrowUp');
    assert(await matches.last().evaluate(node=>node===document.activeElement));
    await page.keyboard.press('ArrowDown');
    assert(await matches.first().evaluate(node=>node===document.activeElement));
    await page.keyboard.press('Escape');
    assert.equal(await search.inputValue(),'');
    assert(await page.locator('#global-search-results').isHidden());
    checked('CRM search handles multiple real results, keyboard wrapping and Escape without changing records');
    const rows = page.locator('tbody tr');
    assert.equal(await rows.count(), 5);
    assert.match(await rows.first().textContent(), /ZZ Med Spa.*85.*85%.*Need unconfirmed/);
    assert.equal(await page.getByText('Need unconfirmed', { exact: true }).count(), 5);
    await page.screenshot({ path: '/out/live-prospects-desktop.png', fullPage: true });
    await page.getByRole('link', { name: 'Leads & research', exact: true }).click();
    await page.getByRole('heading',{name:'Leads & research',exact:true}).waitFor();
    await page.getByRole('button',{name:'Ready for review',exact:true}).click();
    assert.equal(await page.locator('tbody tr').count(),5);
    const names=await page.locator('.lead-link').allTextContents();
    await page.getByLabel('Sort leads',{exact:true}).selectOption('name');
    assert.deepEqual(await page.locator('.lead-link').allTextContents(),[...names].sort((a,b)=>a.localeCompare(b)));
    await page.getByRole('button',{name:'Confirmed needs',exact:true}).click();
    await page.getByRole('heading',{name:'No leads in this view'}).waitFor();
    await page.getByLabel('Sort leads',{exact:true}).selectOption('priority');
    checked('CRM saved views and alphabetical sorting operate on the five real records without creating confirmed needs');
    await page.getByLabel('Filter leads', { exact: true }).selectOption('ready');
    assert.equal(await page.locator('tbody tr').count(), 5);
    await page.getByLabel('Filter leads', { exact: true }).selectOption('confirmed');
    await page.getByRole('heading', { name: 'No leads in this view' }).waitFor();
    await page.getByLabel('Filter leads', { exact: true }).selectOption('all');
    checked('Public queue ranks by contact/business fit; confirmed-gap filter stays empty');
    await page.getByRole('button', { name: 'Tribeca Medspa', exact: true }).click();
    await page.getByRole('heading', { name: 'Two-stage review' }).waitFor();
    const detail = page.locator('#lead-content');
    await detail.getByText('Prospect review ready', { exact: true }).waitFor();
    await detail.getByText('Need unconfirmed', { exact: true }).waitFor();
    assert.match(await detail.textContent(), /646.*687.*9711[\s\S]*212.*925.*9500/);
    assert.equal(await detail.locator('.stat-value').first().textContent(), '40/100');
    assert.equal(await detail.locator('.stat-value').nth(2).textContent(), '0/100');
    await page.getByRole('button', { name: 'Generate outreach draft', exact: true }).click();
    await page.getByLabel('Outreach draft', { exact: true }).waitFor();
    assert.match(await page.getByLabel('Outreach draft', { exact: true }).inputValue(), /I'd like to understand/);
    assert.doesNotMatch(await page.getByLabel('Outreach draft', { exact: true }).inputValue(), /manual inquiry|missed reminders/);
    assert(await page.getByRole('button', { name: 'Create workflow draft', exact: true }).isDisabled());
    await page.screenshot({ path: '/out/live-prospect-detail.png', fullPage: true });
    checked('Real lead keeps phone discrepancy and unknown needs; draft asks questions and workflow is blocked');
    await page.getByRole('button', { name: 'Close', exact: true }).click();
    await page.getByRole('link', { name: 'Overview', exact: true }).click();
    await page.getByRole('heading', { name: 'Overview', exact: true }).waitFor();
    await page.setViewportSize({ width: 390, height: 844 });
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: '/out/live-prospects-mobile.png', fullPage: true });
    await page.getByRole('link', { name: 'Leads & research', exact: true }).click();
    await page.getByRole('button', { name: 'ZZ Med Spa', exact: true }).click();
    await page.getByRole('heading', { name: 'Two-stage review' }).waitFor();
    assert(await page.evaluate(() => document.querySelector('#lead-dialog').scrollWidth <= document.querySelector('#lead-dialog').clientWidth));
    checked('Mobile two-stage workspace and lead dialog fit the viewport');
    assert.deepEqual(errors, []);
    fs.writeFileSync('/out/live-qualification-report.json', JSON.stringify({ checked_at: new Date().toISOString(), checks, javascript_errors: errors, read_only: true, businesses_contacted: false }, null, 2));
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
