// Browser verification through the pinned collector image's existing Playwright.
// Fixture mode REQUIRES an isolated server/database on port 8001. Live mode
// uses port 8000, runs one public collection, and never imports or contacts leads.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const { chromium } = require('/opt/ms-playwright-go/package');

(async () => {
  const mode = process.argv[2] || 'fixture';
  assert(['fixture', 'live'].includes(mode));
  const base = `http://127.0.0.1:${mode === 'fixture' ? 8001 : 8000}`;
  const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
  const page = await context.newPage(), errors = [], checks = [];
  page.on('pageerror', error => errors.push(error.message));
  const checked = name => { checks.push(name); process.stdout.write(`PASS ${name}\n`); };
  const visible = async locator => { await locator.waitFor({ state: 'visible', timeout: 20000 }); };
  const click = async name => page.getByRole('button', { name, exact: true }).click();
  const headers = { Authorization: 'Bearer ui-fixture-access-only' };
  try {
    await page.goto(base + '/app/');
    if (mode === 'fixture') {
      await visible(page.getByRole('dialog', { name: 'Unlock your workspace' }));
      await page.getByLabel('API token', { exact: true }).fill('wrong-fixture-token');
      await click('Unlock workspace');
      await visible(page.locator('#auth-error').filter({ hasText: 'valid API token' }));
      await page.getByLabel('API token', { exact: true }).fill('ui-fixture-access-only');
      await click('Unlock workspace');
      await page.locator('#auth-dialog').waitFor({ state: 'hidden' });
      await visible(page.getByRole('heading', { name: 'Overview', exact: true }));
      assert.equal(await page.locator('.stat-value').first().textContent(), '0');
      checked('Shared-token access rejects wrong token; empty workspace has no invented metrics');
      await page.getByRole('link', { name: 'Discover & import', exact: true }).click();
      const csv = Buffer.from('name,address,website,phone,rating,review_count\nSynthetic Test Med Spa,Fixture Address,https://example.com,+12025550101,4.5,10\n<img src=x onerror=window.UNSAFE_EXECUTED=true>,XSS Fixture Address,https://example.com,,,\nInvalid missing address,,https://example.com,,,\n');
      await page.getByLabel('CSV file', { exact: true }).setInputFiles({ name: 'synthetic-browser-fixture.csv', mimeType: 'text/csv', buffer: csv });
      await click('Preview CSV →');
      await visible(page.getByRole('heading', { name: 'Review before importing' }));
      assert.equal(await page.locator('#preview-region .stat-value').nth(0).textContent(), '2');
      assert.equal(await page.locator('#preview-region .stat-value').nth(2).textContent(), '1');
      assert.equal((await (await context.request.get(base + '/businesses', { headers })).json()).length, 0);
      assert.equal(await page.evaluate(() => window.UNSAFE_EXECUTED), undefined);
      checked('CSV preview reports valid/invalid rows, saves nothing, and renders hostile names as text');
      await page.getByLabel('Export source', { exact: true }).selectOption('web_scraper');
      assert.equal(await page.getByRole('heading', { name: 'Review before importing' }).count(), 0);
      let release, seen;
      const pending = new Promise(resolve => { release = resolve; });
      const requested = new Promise(resolve => { seen = resolve; });
      await page.route('**/businesses/import-csv?**', async route => { seen(); await pending; await route.continue(); });
      await click('Preview CSV →'); await requested;
      await page.getByLabel('Export source', { exact: true }).selectOption('instant_data_scraper');
      release();
      await visible(page.locator('#notice').filter({ hasText: 'changed while the preview was loading' }));
      assert.equal(await page.getByRole('heading', { name: 'Review before importing' }).count(), 0);
      await page.unroute('**/businesses/import-csv?**');
      await page.getByLabel('Export source', { exact: true }).selectOption('web_scraper');
      await click('Preview CSV →');
      await click('Import 2 valid new leads');
      await visible(page.getByRole('heading', { name: 'Import result' }));
      assert.equal((await (await context.request.get(base + '/businesses', { headers })).json()).length, 2);
      checked('Changed settings invalidate previews, including in-flight requests; explicit import saves only valid rows');
      await page.getByRole('link', { name: 'Leads & research', exact: true }).click();
      await page.getByRole('button', { name: 'Synthetic Test Med Spa', exact: true }).click();
      await visible(page.getByRole('heading', { name: 'This lead needs its first analysis' }));
      await click('Analyze listing only');
      await visible(page.getByRole('heading', { name: 'Evidence & unknowns' }));
      assert.equal(await page.locator('#lead-content .stat-value').nth(2).textContent(), '0/100');
      const booking = page.locator('.evidence-item').filter({ hasText: 'Booking friction' });
      assert.match(await booking.textContent(), /Unknown/);
      checked('Listing-only analysis leaves operational need and booking journey unknown');
      await page.getByText('Record or update evidence', { exact: true }).click();
      await page.getByLabel('Criterion', { exact: true }).selectOption('operational_scale');
      await page.getByLabel('Assessment', { exact: true }).selectOption('strong');
      await page.getByLabel('Source', { exact: true }).selectOption('public_website');
      await page.getByLabel('Evidence details', { exact: true }).fill('Synthetic fixture only: five practitioners listed. No internal processes were established.');
      await click('Save evidence & recalculate');
      await visible(page.locator('#lead-content').getByText('Prospect review ready', { exact: true }));
      await visible(page.locator('#lead-content').getByText('Need unconfirmed', { exact: true }));
      assert.equal(await page.locator('#lead-content .stat-value').nth(0).textContent(), '40/100');
      assert.equal(await page.locator('#lead-content .stat-value').nth(1).textContent(), '40%');
      assert.equal(await page.locator('#lead-content .stat-value').nth(2).textContent(), '0/100');
      checked('Public fit makes a prospect reviewable while its internal need remains unconfirmed');
      await click('Generate outreach draft');
      await visible(page.getByLabel('Outreach draft', { exact: true }));
      assert.match(await page.getByLabel('Outreach draft', { exact: true }).inputValue(), /I'd like to understand/);
      assert.doesNotMatch(await page.getByLabel('Outreach draft', { exact: true }).inputValue(), /five practitioners|manual inquiry follow-up/);
      assert(await page.getByRole('button', { name: 'Create workflow draft', exact: true }).isDisabled());
      checked('Pre-confirmation outreach asks about processes; a public-ready prospect cannot create a need-based workflow');
      await page.getByText('Record or update evidence', { exact: true }).click();
      await page.getByLabel('Assessment', { exact: true }).selectOption('strong');
      assert.equal(await page.getByLabel('Source', { exact: true }).inputValue(), 'business_confirmation');
      assert.equal(await page.getByLabel('Source', { exact: true }).isDisabled(), true);
      await page.getByLabel('Evidence details', { exact: true }).fill('Synthetic fixture conversation only: manual inquiry follow-up confirmed for testing, not a real business.');
      await page.getByText('The business actually confirmed this process; the details identify the conversation or source.', { exact: true }).click();
      await click('Save evidence & recalculate');
      await visible(page.getByRole('heading', { name: 'Evidence & unknowns' }));
      await visible(page.getByText('Synthetic fixture conversation only: manual inquiry follow-up confirmed for testing, not a real business.', { exact: true }));
      await visible(page.locator('#lead-content').getByText('Business-confirmed gap', { exact: true }));
      assert.equal(await page.locator('#lead-content .stat-value').nth(0).textContent(), '40/100');
      checked('Evidence editing requires business confirmation for an operational gap and persists the observation');
      let refreshBody;
      await page.route('**/businesses/*/analyze', async route => {
        refreshBody = route.request().postDataJSON();
        await route.fulfill({ status: 422, contentType: 'application/json', body: JSON.stringify({ error: { message: 'Synthetic fixture: website network request intentionally blocked.' } }) });
      });
      await click('Fetch website & analyze');
      await visible(page.locator('#notice').filter({ hasText: 'Synthetic fixture: website network request intentionally blocked.' }));
      assert.equal(refreshBody.fetch_website, true);
      assert(refreshBody.evidence.every(item => item.origin !== 'automatic'));
      assert(refreshBody.evidence.some(item => item.criterion === 'inquiry_followup' && item.origin === 'operator' && item.source === 'business_confirmation'));
      await page.unroute('**/businesses/*/analyze');
      checked('Website refresh replaces automatic evidence and retains operator confirmation without an external fixture request');
      await page.getByLabel('Stage', { exact: true }).selectOption('interested');
      await page.getByLabel('Notes', { exact: true }).fill('Synthetic UI test note. No contact occurred.');
      await click('Save contact record');
      await visible(page.locator('#notice').filter({ hasText: 'Contact stage and notes saved' }));
      await click('Generate outreach draft');
      await visible(page.getByLabel('Outreach draft', { exact: true }));
      assert.match(await page.getByLabel('Outreach draft', { exact: true }).inputValue(), /Synthetic Test Med Spa/);
      const download = page.waitForEvent('download'); await click('Create workflow draft'); await download;
      await click('Close');
      await page.getByRole('button', { name: 'Synthetic Test Med Spa', exact: true }).click();
      await visible(page.getByLabel('Stage', { exact: true }));
      assert.equal(await page.getByLabel('Stage', { exact: true }).inputValue(), 'interested');
      assert.equal(await page.getByLabel('Notes', { exact: true }).inputValue(), 'Synthetic UI test note. No contact occurred.');
      await click('Close');
      await page.getByRole('link', { name: 'Workflow drafts', exact: true }).click();
      await visible(page.getByText('Draft · not running', { exact: true }));
      await click('Archive');
      await visible(page.getByText('Archived · not running', { exact: true }));
      checked('Contact notes survive reopening; outreach remains a draft; workflow export and archive work');
      await page.getByRole('link', { name: 'Leads & research', exact: true }).click();
      await page.getByRole('button', { name: 'Synthetic Test Med Spa', exact: true }).click();
      await visible(page.getByLabel('Stage', { exact: true }));
      await page.getByLabel('Stage', { exact: true }).selectOption('do_not_contact');
      await click('Save contact record');
      await visible(page.locator('#lead-content').getByText('This lead is marked do not contact. Outreach drafts are blocked.', { exact: true }));
      assert(await page.getByRole('button', { name: 'Generate outreach draft', exact: true }).isDisabled());
      assert(await page.getByRole('button', { name: 'Create workflow draft', exact: true }).isDisabled());
      const blocked = (await (await context.request.get(base + '/prospects?include_blocked=true', { headers })).json()).find(q => q.prospect_status === 'do_not_contact');
      const draftResponse = await context.request.get(`${base}/businesses/${blocked.business_id}/outreach-draft?analysis_id=${blocked.analysis_id}`, { headers });
      assert.equal(draftResponse.status(), 409);
      const workflowResponse = await context.request.post(base + '/workflows', { headers, data: { analysis_id: blocked.analysis_id } });
      assert.equal(workflowResponse.status(), 409);
      await page.getByLabel('Stage', { exact: true }).selectOption('interested');
      await click('Save contact record');
      await visible(page.locator('#notice').filter({ hasText: 'Contact stage and notes saved' }));
      await click('Close');
      checked('Do-not-contact updates block outreach and new workflow drafts in both UI and API');
      await page.getByRole('button', { name: 'Synthetic Test Med Spa', exact: true }).click();
      await visible(page.getByLabel('Notes', { exact: true }));
      let releaseContact, sawContact;
      const pendingContact = new Promise(resolve => { releaseContact = resolve; });
      const contactRequested = new Promise(resolve => { sawContact = resolve; });
      await page.route('**/businesses/*/contact', async route => {
        if (route.request().method() === 'PATCH') { sawContact(); await pendingContact; }
        await route.continue();
      });
      await page.getByLabel('Notes', { exact: true }).fill('Synthetic pending-save fixture. No contact occurred.');
      await click('Save contact record'); await contactRequested;
      await click('Close'); releaseContact();
      await visible(page.locator('#notice').filter({ hasText: 'Contact stage and notes saved' }));
      assert.equal(await page.locator('#lead-dialog').isVisible(), false);
      await page.unroute('**/businesses/*/contact');
      checked('Closing a lead during a pending save keeps it closed when the save completes');
      await context.request.post(base + '/businesses/import', { headers, data: { industry: 'med spa', location: 'Synthetic Fixture City' } });
      await page.getByRole('button', { name: 'Refresh workspace', exact: true }).click();
      await page.getByRole('link', { name: 'Leads & research', exact: true }).click();
      assert.equal(await page.getByRole('button', { name: /Demo Glow/ }).count(), 0);
      await page.getByLabel('Include fictional demo leads', { exact: true }).check();
      await visible(page.getByRole('button', { name: /Demo Glow/ }));
      assert(await page.getByText('Demo · fictional', { exact: true }).count() >= 1);
      await page.getByLabel('Include fictional demo leads', { exact: true }).uncheck();
      checked('Demo leads are excluded by default and explicitly labeled when included');
      await page.route('**/ready', route => route.abort());
      await page.getByRole('button', { name: 'Refresh workspace', exact: true }).click();
      await visible(page.getByText(/The data below is from the last successful load/));
      await page.unroute('**/ready');
      await page.getByRole('button', { name: 'Refresh workspace', exact: true }).click();
      await visible(page.getByText('SQLite connected', { exact: true }));
      checked('Connection failures label previously loaded data as stale; refresh recovers');
      await page.getByRole('link', { name: 'Overview', exact: true }).click();
      await visible(page.getByRole('heading', { name: 'Overview', exact: true }));
      await page.screenshot({ path: '/out/fixture-desktop.png', fullPage: true });
      await page.getByRole('button', { name: 'Lock', exact: true }).click();
      await visible(page.getByRole('dialog', { name: 'Unlock your workspace' }));
      assert.equal(await page.locator('#lead-content').textContent(), '');
      assert.equal(await page.evaluate(() => localStorage.length + sessionStorage.length), 0);
      checked('Lock clears rendered lead data and token is never saved in browser storage');
    } else {
      await visible(page.getByRole('heading', { name: 'Overview', exact: true }));
      assert.equal(await page.locator('.stat-value').nth(0).textContent(), '5');
      assert.equal(await page.locator('.stat-value').nth(2).textContent(), '0');
      await page.screenshot({ path: '/out/live-desktop.png', fullPage: true });
      checked('Live workspace shows five real imported leads and zero confirmed opportunities');
      await page.getByRole('link', { name: 'Leads & research', exact: true }).click();
      await page.getByRole('button', { name: 'Tribeca Medspa', exact: true }).click();
      await visible(page.getByRole('heading', { name: 'Evidence & unknowns' }));
      assert.match(await page.locator('#lead-content').textContent(), /646.*687.*9711[\s\S]*212.*925.*9500/);
      await page.screenshot({ path: '/out/live-lead.png', fullPage: true });
      await click('Close');
      checked('Real evidence retains the Maps-versus-website phone discrepancy');
      await page.getByRole('button', { name: 'Dolce Medical Spa NYC', exact: true }).click();
      await visible(page.getByRole('heading', { name: 'Evidence & unknowns' }));
      const response = page.waitForResponse(r => r.url().endsWith('/analyze') && r.request().method() === 'POST', { timeout: 120000 });
      await click('Fetch website & analyze');
      const actual = await response;
      assert.equal(actual.status(), 201); const analysis = await actual.json();
      assert(analysis.website?.url.startsWith('https://dolcemedicalspas.com/'));
      assert.equal(analysis.components.N, 0); assert(analysis.provisional);
      await visible(page.getByRole('heading', { name: 'Last website snapshot' }));
      await click('Close');
      checked('Browser action fetches the real official website, saves analysis, and preserves unknown internal needs');
      await page.getByRole('link', { name: 'Discover & import', exact: true }).click();
      await page.getByLabel('Business + location query', { exact: true }).fill('medical spas in New York NY');
      await page.getByLabel('Maximum listings', { exact: true }).fill('1');
      await click('Start live pilot →');
      await page.getByText('Succeeded', { exact: true }).first().waitFor({ timeout: 350000 });
      await page.getByRole('button', { name: 'Preview results', exact: true }).first().click();
      await visible(page.getByRole('heading', { name: 'Review before importing' }));
      assert.equal(await page.locator('#preview-region .stat-value').nth(3).textContent(), '1');
      assert.equal((await (await context.request.get(base + '/businesses')).json()).filter(b => b.source !== 'mock').length, 5);
      await page.screenshot({ path: '/out/live-pilot.png', fullPage: true });
      checked('Live browser pilot collects one real listing; preview is displayed and no leads auto-import');
      await page.getByRole('link', { name: 'Overview', exact: true }).click();
      await visible(page.getByRole('heading', { name: 'Overview', exact: true }));
      await page.setViewportSize({ width: 390, height: 844 });
      await page.screenshot({ path: '/out/live-mobile.png', fullPage: true });
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
      await page.getByRole('link', { name: 'Leads & research', exact: true }).click();
      await page.getByRole('button', { name: 'ZZ Med Spa', exact: true }).click();
      await visible(page.getByRole('heading', { name: 'Evidence & unknowns' }));
      assert(await page.evaluate(() => document.querySelector('#lead-dialog').scrollWidth <= document.querySelector('#lead-dialog').clientWidth));
      checked('Mobile overview and lead dialog fit the viewport without page overflow');
    }
    assert.deepEqual(errors, [], 'Unexpected browser JavaScript errors');
    fs.writeFileSync(`/out/${mode}-report.json`, JSON.stringify({ mode, checks, javascript_errors: errors, checked_at: new Date().toISOString(), businesses_contacted: false, workflow_execution: false }, null, 2));
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
